\i sql/00_drop_database
\i sql/01_create_roles.sql
\i sql/02_create-database.sql
\i sql/00_init/03_extensions.sql
\i sql/00_init/04_search_path.sql
\i sql/10_schema/01_create_schema.sql
\i sql/20_tables/activity.sql
\i sql/20_tables/activity_historique.sql
\i sql/20_tables/activity_batch_report.sql
\i sql/20_tables/actuator.sql
\i sql/20_tables/actuator_info.sql
\i sql/20_tables/anomalie.sql
\i sql/20_tables/anomalie_details.sql
\i sql/20_tables/batch.sql
\i sql/20_tables/batch_traitement.sql
\i sql/20_tables/batch_execution.sql
\i sql/20_tables/batch_execution_journal.sql
\i sql/20_tables/batch_profiling.sql
\i sql/20_tables/groupe.sql
\i sql/20_tables/historique.sql
\i sql/20_tables/hotspot_details.sql
\i sql/20_tables/hotspot_owasp.sql
\i sql/20_tables/hotspots.sql
\i sql/20_tables/information_projet.sql
\i sql/20_tables/liste_projet.sql
\i sql/20_tables/logger.sql
\i sql/20_tables/ma_moulinette.sql
\i sql/20_tables/mesures.sql
\i sql/20_tables/no_sonar.sql
\i sql/20_tables/notes.sql
\i sql/20_tables/owasp.sql
\i sql/20_tables/owasp_top10.sql
\i sql/20_tables/portefeuille.sql
\i sql/20_tables/portefeuille_historique.sql
\i sql/20_tables/profiles.sql
\i sql/20_tables/profiles_historique.sql
\i sql/20_tables/properties.sql
\i sql/20_tables/repartition.sql
\i sql/20_tables/todo.sql
\i sql/20_tables/utilisateur.sql
\i sql/30_views/vw_batch_profiling_global.sql
\i sql/30_views/vw_batch_profiling_monthly.sql
\i sql/30_views/vw_batch_profiling_stats.sql
\i sql/30_views/vw_batch_profiling_summary.sql
\i sql/30_views/vw_batch_profiling_weekly.sql
\i sql/40_indexes/indexes.sql
\i sql/50_functions/get_pg_stat_activity.sql
\i sql/60_comments/comments.sql
\i sql/70_constraints/constraints.sql
\i sql/80_grants/grants.sql
\i sql/90_fixtures/fixtures.sql
