---
doctrine_migrations:
    migrations_paths:
        'MigrationsDefault': '%kernel.project_dir%/migrations/default'
        'MigrationsSecondary': '%kernel.project_dir%/migrations/secondary'
    enable_profiler: true
    check_database_platform: true
...
