---
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_DEFAULT_URL)%'
                driver: pdo_sqlite
                host: 127.0.0.1
                charset: UTF8
                server_version: '4'
            secondary:
                url: '%env(resolve:DATABASE_SECONDARY_URL)%'
                driver: pdo_sqlite
                host: 127.0.0.1
                charset: UTF8
                server_version: '4'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            secondary:
                connection: secondary
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Seondary:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Secondary'
                        prefix: 'App\Entity\Secondary'
                        alias: Secondary
...
