---
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_sqlite
        host: 127.0.0.1
        charset: UTF8
        server_version: '4'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
...
