---
doctrine_migrations:
#    em: default
    migrations_paths:
        'DefaultMigrations': '%kernel.project_dir%/migrations/default'
        'SecondaryMigrations': '%kernel.project_dir%/migrations/secondary'
    enable_profiler: '%kernel.debug%'
...
