---
monolog:
    channels:
        - deprecation # Pour capturer les dépréciations
        - doctrine
        - messenger

    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        doctrine:
            type: stream
            path: '%kernel.logs_dir%/doctrine.log'
            level: debug
            channels: ['doctrine']
        messenger:
            type: stream
            path: '%kernel.logs_dir%/messenger.log'
            level: debug
            channels: ['messenger']

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: ['!event']
            console:
                type: console
                process_psr_3_messages: false
                channels: ['!event', '!doctrine', '!console']
            messenger:
                type: stream
                path: '%kernel.logs_dir%/messenger_dev.log'
                level: debug
                channels: ['messenger']

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ['!event']
            nested:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
            doctrine:
                type: stream
                path: '%kernel.logs_dir%/doctrine_test.log'
                level: debug
                channels: ['doctrine']

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # Évite les fuites de mémoire
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ['!event', '!doctrine']
            deprecation:
                type: stream
                channels: ['deprecation']
                path: php://stderr
            messenger:
                type: stream
                path: '%kernel.logs_dir%/messenger_prod.log'
                level: debug
                channels: ['messenger']
            doctrine:
                type: stream
                path: '%kernel.logs_dir%/doctrine_prod.log'
                level: error
                channels: ['doctrine']
...
