---
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: ma-moulinette.yaml }
parameters:
    # SonarQube
    sonar.version: '%env(SONAR_VERSION)%'
    sonar.url: '%env(SONAR_URL)%'
    sonar.token: '%env(SONAR_TOKEN)%'
    sonar.user: '%env(SONAR_USER)%'
    sonar.password: '%env(SONAR_PASSWORD)%'

    sonar.activity.token: '%env(SONAR_ACTIVITY_TOKEN)%'
    sonar.activity.user: '%env(SONAR_ACTIVITY_USER)%'
    sonar.activity.password: '%env(SONAR_ACTIVITY_USER)%'

    sonar.profiles: '%env(SONAR_PROFILES)%'
    sonar.organization: '%env(SONAR_ORGANIZATION)%'
    nombre.favori: '%env(NOMBRE_FAVORI)%'

    #Paramètre HTTP
    ciphers: '%env(CIPHERS)%'
    verify.host: '%env(VERIFY_HOST)%'
    verify.peer: '%env(VERIFY_PEER)%'

    # Plugin SonarQube (optionnel)
    track.logger.method: '%env(TRACK_LOGGER_METHOD)%'

    # Gestion des projets et profils
    maj.projet: '%env(MAJ_PROJET)%'
    maj.profil: '%env(MAJ_PROFIL)%'

    # Traitement
    csrf.salt: '%env(CSRF_SALT)%'
    path.audit: '%env(PATH_AUDIT)%'

    # Copyright | Entreprise
    marque.entreprise.short: '%env(MARQUE_ENTREPRISE_SHORT)%'
    marque.entreprise.long: '%env(MARQUE_ENTREPRISE_LONG)%'

    # Environnement
    environnement: '%env(ENVIRONNEMENT)%'

    # Logo Entreprise
    logo.entreprise: '%env(LOGO_ENTREPRISE)%'

    # RGA
    rgaa: '%env(RGAA)%'

    # CGU
    cgu.editeur: '%env(CGU_EDITEUR)%'
    cgu.adresse: '%env(CGU_ADRESSE)%'
    cgu.siret: '%env(CGU_SIRET)%'
    cgu.siren: '%env(CGU_SIREN)%'
    cgu.numero.siret: '%env(CGU_NUMERO_SIRET)%'
    cgu.numero.siren: '%env(CGU_NUMERO_SIREN)%'
    cgu.directeur.publication: '%env(CGU_DIRECTEUR_PUBLICATION)%'
    cgu.source.url: '%env(CGU_SOURCE_URL)%'
    cgu.source.scm: '%env(CGU_SOURCE_SCM)%'
    cgu.hebergement: '%env(CGU_HEBERGEMENT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Services explicites
    App\Service\RabbitMQService:
        arguments:
            $host: '%env(RABBITMQ_HOST)%'
            $port: '%env(int:RABBITMQ_PORT)%'
            $user: '%env(RABBITMQ_USER)%'
            $password: '%env(RABBITMQ_PASSWORD)%'
            $vhost: '%env(RABBITMQ_VHOST)%'

    # POur les TU
    App\Controller\Batch\BatchCollecteTodoController:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $client: '@App\Service\Client'
        tags: ['controller.service_arguments']
...
