---
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: ma-moulinette.yaml }
parameters:
    # SonarQube
    sonar.url: '%env(SONAR_URL)%'
    sonar.token: '%env(SONAR_TOKEN)%'
    sonar.user: '%env(SONAR_USER)%'
    sonar.password: '%env(SONAR_PASSWORD)%'
    sonar.profiles: '%env(SONAR_PROFILES)%'
    sonar.organization: '%env(SONAR_ORGANIZATION)%'
    nombre.favori: '%env(NOMBRE_FAVORI)%'

    # Gestion des projets et profils
    maj.projet: '%env(MAJ_PROJET)%'
    maj.profil: '%env(MAJ_PROFIL)%'

    # Traitement
    csrf.salt: '%env(CSRF_SALT)%'
    path.audit: '%env(PATH_AUDIT)%'

    # RGA
    rgaa: '%env(RGAA)%'

    # CGU
    cgu.editeur: '%env(CGU_EDITEUR)%'
    cgu.adresse: '%env(CGU_ADRESSE)%'
    cgu.siret: '%env(CGU_SIRET)%'
    cgu.siren: '%env(CGU_SIREN)%'
    cgu.numero.siret: '%env(CGU_NUMERO_SIRET)%'
    cgu.numero.siren: '%env(CGU_NUMERO_SIREN)%'
    cgu.directeur.publication: '%env(CGU_DIRECTEUR_PUBLICATION)%'
    cgu.source.url: '%env(CGU_SOURCE_URL)%'
    cgu.source.scm: '%env(CGU_SOURCE_SCM)%'
    cgu.hebergement: '%env(CGU_HEBERGEMENT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Services explicites
    App\Service\RabbitMQService:
        arguments:
            $host: '%env(RABBITMQ_HOST)%'
            $port: '%env(int:RABBITMQ_PORT)%'
            $user: '%env(RABBITMQ_USER)%'
            $password: '%env(RABBITMQ_PASSWORD)%'
            $vhost: '%env(RABBITMQ_VHOST)%'
...
