/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.2 - 14/07/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
--- On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.
-- 2026-07-14 : ajustement de la taille de la colonne analyse_id (40) pour supporter les UUID de SonarQube 2026.2.0 et submitter_login (100) pour supporter les logins LDAP de SonarQube 2026.2.0 et project_name (255) pour supporter les noms de projet SonarQube 2026.2.0.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.activity;

CREATE TABLE ma_moulinette.activity
(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  analyse_id VARCHAR(40) NOT NULL,
  status VARCHAR(16) NOT NULL,
  submitter_login VARCHAR(100) NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL,
  execution_time INT NOT NULL
);
