/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.1.0 - 23/07/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
--- On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.
--- 2026-07-23 : Renommage actuator_info_value en actuator_info_cle

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema

\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.actuator_info;

CREATE TABLE ma_moulinette.actuator_info
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actuator_info_description VARCHAR(255),
    actuator_info_cle VARCHAR(128),
    actuator_id INT NOT NULL
);
