/*
####################################################
##                                                ##
##           Create TABLE                         ##
##           clean_code                           ##
##           V1.0.0 - 2026-05-17                  ##
##                                                ##
####################################################*/

-- MODIF 2026-05-17 : nouvelle table pour stocker
-- les indicateurs SonarQube 10+ : cleanCodeAttributeCategories,
-- impactSeverities, impactSoftwareQualities et standards de conformité
-- OWASP Top 10 2021 / SANS Top 25 / CWE.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.clean_code;

CREATE TABLE ma_moulinette.clean_code
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  project_name VARCHAR(128) NOT NULL,
  -- Total issues (paging.total de l'appel principal)
  issue_total INT NOT NULL DEFAULT 0,
  -- Clean Code Attribute Categories (SonarQube 10+)
  cc_consistent INT NOT NULL DEFAULT 0,
  cc_intentional INT NOT NULL DEFAULT 0,
  cc_adaptable INT NOT NULL DEFAULT 0,
  cc_responsible INT NOT NULL DEFAULT 0,
  -- Impact Software Qualities (SonarQube 10+)
  quality_maintainability INT NOT NULL DEFAULT 0,
  quality_reliability INT NOT NULL DEFAULT 0,
  quality_security INT NOT NULL DEFAULT 0,
  -- Impact Severities — 5 niveaux SonarQube 10+ (BLOCKER/HIGH/MEDIUM/LOW/INFO)
  impact_blocker INT NOT NULL DEFAULT 0,
  impact_high INT NOT NULL DEFAULT 0,
  impact_medium INT NOT NULL DEFAULT 0,
  impact_low INT NOT NULL DEFAULT 0,
  impact_info INT NOT NULL DEFAULT 0,
  -- Standards de conformité
  owasp_top10 INT NOT NULL DEFAULT 0,
  sans_top25 INT NOT NULL DEFAULT 0,
  cwe INT NOT NULL DEFAULT 0,
  -- Méta collecte
  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
