/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.1 - 2026-05-18                  ##
##                                                ##
##                                                ##
####################################################*/

--- 2026-05-08 : référentiel global des CVE.
--- Une row = une CVE unique (deduplication par cve_id).
--- Permet la vue agrégée : "combien de projets touches par CVE-X".
--- 2026-05-18 : Suppression de la dernière virgule de la ligne "updated_at" (dernière colonne) pour éviter les erreurs de syntaxe SQL.

-- Identifiant CVE unique (CVE-YYYY-NNNNN ou GHSA-xxxx pour GitHub Advisory)
-- Source du referentiel : NVD | OSSINDEX | NPM | RETIREJS | GITHUB
-- Severity globale (CRITICAL | HIGH | MEDIUM | LOW | INFO | UNKNOWN)
-- CVSS v3 details
-- CWEs : array natif PG des identifiants CWE-XXX (peut être vide)
-- JSONB choisi pour garder le format brut DC compatible (string array)
-- Description complete + references
-- liste {source, url, name}
-- Traçabilité : premiere et dernière apparition dans nos scans
-- Date de dernière maj des donnees NVD (si on resync un jour)

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.dc_cve CASCADE;

CREATE TABLE ma_moulinette.dc_cve
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cve_id VARCHAR(64) NOT NULL,
  source VARCHAR(32) NOT NULL,
  severity VARCHAR(16) NOT NULL,
  cvss_v3_score NUMERIC(3, 1) NULL,         -- 0.0 a 10.0
  cvss_v3_severity VARCHAR(16) NULL,
  cvss_v3_attack_vector VARCHAR(32) NULL,
  cvss_v3_attack_complexity VARCHAR(32) NULL,
  cvss_v3_vector VARCHAR(255) NULL,
  cwes JSONB NOT NULL DEFAULT '[]'::jsonb,
  description  TEXT NOT NULL DEFAULT '',
  cve_references JSONB NOT NULL DEFAULT '[]'::jsonb,
  first_seen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  last_seen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
);
