/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.1 - 2026-05-18                  ##
##                                                ##
##                                                ##
####################################################*/

--- 2026-05-08 : référentiel des dépendances analysées.
--- Une row = une dépendance unique (deduplication par sha1, cle naturelle).
--- Permet la vue agrégée : "quelles deps vulnérables sont les plus répandues".
--- 2026-05-18 : Suppression de la dernière virgule de la ligne "last_seen_at" (dernière colonne) pour éviter les erreurs de syntaxe SQL.

-- Cle naturelle : sha1 du fichier (le meme .jar partage le même sha1 partout)
-- Hashes complémentaires pour verification croisée
-- Identité humaine de la dépendance
-- File_name, ex: amqp-client-5.9.0.jar
-- Pkg_coordinates, ex: pkg:maven/com.rabbitmq/amqp-client@5.9.0
-- Donnees découpées pour requêtes (extraites des packages[].id ou de evidenceCollected)
-- vendor, ex: com.rabbitmq
-- product, ex: amqp-client
-- version, ex: 5.9.0

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.dc_dependency CASCADE;

CREATE TABLE ma_moulinette.dc_dependency
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sha1 CHAR(40) NOT NULL,
  md5 CHAR(32) NULL,
  sha256 CHAR(64) NULL,
  file_name VARCHAR(512) NOT NULL,
  pkg_coordinates VARCHAR(512) NULL,
  vendor VARCHAR(255) NULL,
  product VARCHAR(255) NULL,
  version VARCHAR(64)  NULL,
  license VARCHAR(255) NULL,
  description TEXT NULL,
  first_seen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  last_seen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
);
