/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.1 - 2026-05-18                  ##
##                                                ##
##                                                ##
####################################################*/

--- 2026-05-08 : jointure ternaire scan x dependency x cve.
--- 2026-05-18 : Suppression de la dernière virgule de la ligne "created_at" (dernière colonne) pour éviter les erreurs de syntaxe SQL.

--- Snapshot severity/cvss au moment du scan (NVD peut requalifier plus tard).
--- C'est dans cette table qu'on fait les requêtes croisées pour la vue agrégée.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.dc_finding CASCADE;

CREATE TABLE ma_moulinette.dc_finding
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id BIGINT NOT NULL,
  dependency_id BIGINT NOT NULL,
  cve_id BIGINT NOT NULL,
  severity_at_scan VARCHAR(16) NOT NULL,
  cvss_at_scan NUMERIC(3, 1) NULL,
  fixed_version VARCHAR(64) NULL,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
);
