/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.1.0 - 2026-05-12                  ##
##           dc-ingest : OWASP DependencyCheck    ##
##                                                ##
####################################################*/

--- 2026-05-08 : queue d'ingestion des rapports OWASP DependencyCheck.
---  - reception via POST /api/secure/dependency-check/upload
---  - payload conserve compresse (gzip) en BYTEA pour reprocess et audit
---  - workflow : queued -> processing -> done | failed
---  - idempotence native : UNIQUE(payload_sha256)
--- 2026-05-12 : ajout de metadata parent_label/version et archetype_version transmises par les headers HTTP a l'upload, transportées telles quelles vers dc_scan a l'ingestion.

-- Identifiant public (ULID 26 chars Crockford base32) renvoyé au client
-- Payload OWASP DependencyCheck JSON, gzippé (gzencode niveau 6)
-- PG TOAST géré automatiquement le stockage hors-ligne pour BYTEA > 2 KB
-- sha256 du JSON décompressé (idempotence + traçabilité)
-- Taille du JSON décompressé en octets (pour métrologie)
-- Format reçu : json | gzip | zip | tgz
-- Identification projet extraite de projectInfo
-- Workflow : queued | processing | done | failed
-- Compteur de tentatives (incrémente a chaque claim)
-- Horodatages cycle de vie (precision seconde, alignée sur Doctrine TIMESTAMP(0))
-- Message d'erreur pour les status=failed

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.dc_processing_queue;

CREATE TABLE ma_moulinette.dc_processing_queue
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ulid              VARCHAR(26) NOT NULL UNIQUE,
  payload_gz        BYTEA NOT NULL,
  payload_sha256    CHAR(64) NOT NULL,
  payload_size      INTEGER NOT NULL,
  content_type      VARCHAR(16) NOT NULL,
  project_group     VARCHAR(255) NOT NULL,
  project_artifact  VARCHAR(255) NOT NULL,
  project_version   VARCHAR(64)  NOT NULL,
  status            VARCHAR(16) NOT NULL DEFAULT 'queued',
  attempts          INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  started_at        TIMESTAMP(0) WITH TIME ZONE NULL,
  processed_at      TIMESTAMP(0) WITH TIME ZONE NULL,
  error_message     TEXT NULL,
  -- 2026-05-12 : métadonnées pom.xml transmises par les headers HTTP
  -- X-Parent-Label, X-Parent-Version, X-Archetype-Version lors de l'upload.
  -- Transportées telles quelles vers dc_scan a l'ingestion.
  parent_label      VARCHAR(128) NULL,
  parent_version    VARCHAR(64)  NULL,
  archetype_version VARCHAR(64)  NULL
);
