/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.0 - 04/04/2026                  ##
##                                                ##
####################################################*/

--- 2026-04-04 : Ajout de la table groupe_utilisateur

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.groupe_utilisateur;

CREATE TABLE ma_moulinette.groupe_utilisateur
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  groupe_utilisateur character varying(64) NOT NULL,
  groupe_id character varying(26) NOT NULL,
  description character varying(255) NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
