/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.2 - 05/05/2026                  ##
##                                                ##
####################################################*/

--- 2026-04-05 : Ajout de la table groupe_fonctionnel
--- 2026-05-05 : description VARCHAR(255) -> VARCHAR(128) pour aligner avec l’entité GroupeFonctionnel (length: 128 + Assert\Length(max: 128)).
--- 2026-05-05 : groupe_fonctionnel VARCHAR(128) -> VARCHAR(32) pour aligner avec Validator max: 32.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.groupe_fonctionnel;

CREATE TABLE ma_moulinette.groupe_fonctionnel
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  groupe_fonctionnel character varying(32) NOT NULL,
  description character varying(128) NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
