/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.1.0 - 04/05/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-05-04 : colonnes `date`/`type` renommées en `date_analyse`/`type_analyse`
---              pour cohérence avec comments.sql, indexes.sql et l'entité Doctrine.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.information_projet;

CREATE TABLE ma_moulinette.information_projet
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    maven_key VARCHAR(255) NOT NULL,
    analyse_key VARCHAR(64) NOT NULL,
    date_analyse TIMESTAMPTZ NOT NULL,
    project_version VARCHAR(32) NOT NULL,
    type_analyse VARCHAR(32) NOT NULL,

    version_sonar INT NOT NULL DEFAULT 0,
    version_release_sonar INT NOT NULL DEFAULT 0,
    version_snapshot_sonar INT NOT NULL DEFAULT 0,
    version_autre_sonar INT NOT NULL DEFAULT 0,

    mode_collecte VARCHAR(32),
    utilisateur_collecte VARCHAR(320),

    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
