/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
---              On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;
DROP TABLE IF EXISTS ma_moulinette.no_sonar;

CREATE TABLE ma_moulinette.no_sonar
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  rule VARCHAR(128) NOT NULL,
  component text NOT NULL,
  line INT NOT NULL,
  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
