/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
---              On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.profiles;

CREATE TABLE ma_moulinette.profiles
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key VARCHAR(56) NOT NULL,
  name VARCHAR(128) NOT NULL,
  language_name VARCHAR(64) NOT NULL,
  active_rule_count INT NOT NULL,
  rules_updated_at TIMESTAMPTZ NOT NULL,
  referential_default BOOLEAN NOT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
