/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
---              On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.profiles_historique;

CREATE TABLE ma_moulinette.profiles_historique
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_courte TIMESTAMPTZ NOT NULL,
    language VARCHAR(16) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    action VARCHAR(16) NOT NULL,
    auteur VARCHAR(64) NOT NULL,
    rule VARCHAR(128) NOT NULL,
    description text NOT NULL,
    detail bytea NOT NULL,
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
