
/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
---              On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.repartition_temp;

CREATE UNLOGGED TABLE ma_moulinette.repartition_temp (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maven_key VARCHAR(255) NOT NULL,
    component TEXT NOT NULL,
    type VARCHAR(16) NOT NULL,
    severity VARCHAR(8) NOT NULL,
    setup BIGINT NOT NULL
);
