/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.0 - 24/04/2026                  ##
##                                                ##
####################################################*/

--- 2026-04-24 : Ajout de la table user_role_log (traçage des changements de rôles/activations par l'admin)

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.user_role_log;

CREATE TABLE ma_moulinette.user_role_log
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email VARCHAR(320) NOT NULL,
  editor_email VARCHAR(320) NOT NULL,
  old_roles JSON NOT NULL,
  new_roles JSON NOT NULL,
  old_active BOOLEAN NOT NULL,
  new_active BOOLEAN NOT NULL,
  alerts JSON DEFAULT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
