/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.activity_historique;

CREATE TABLE ma_moulinette.activity_historique
(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INT NOT NULL,
  day INT NOT NULL,
  "analyse" INT NOT NULL,
  analyse_average DOUBLE PRECISION NOT NULL,
  success INT NOT NULL,
  failed INT NOT NULL,
  success_rate DOUBLE PRECISION NOT NULL,
  max_time INT NOT NULL,
  date_enregistrement timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
