/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.activity_batch_report;

CREATE TABLE ma_moulinette.activity_batch_report (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_start TIMESTAMPTZ NOT NULL,
    date_end TIMESTAMPTZ NOT NULL,
    task_count INT NOT NULL DEFAULT 0,
    task_done INT NOT NULL DEFAULT 0,
    page INT NOT NULL DEFAULT 0,
    last_error JSON DEFAULT '[]'::json,
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
