/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
--- On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.


-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.activity;

CREATE TABLE ma_moulinette.activity
(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  project_name VARCHAR(64) NOT NULL,
  analyse_id VARCHAR(26) NOT NULL,
  status VARCHAR(16) NOT NULL,
  submitter_login VARCHAR(32) NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL,
  execution_time INT NOT NULL
);
