/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.activity;

CREATE TABLE ma_moulinette.activity
(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  project_name VARCHAR(64) NOT NULL,
  analyse_id VARCHAR(26) NOT NULL,
  status VARCHAR(16) NOT NULL,
  submitter_login VARCHAR(32) NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL,
  execution_time INT NOT NULL
);
