/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
--- On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema

\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.activity_historique;

CREATE TABLE ma_moulinette.activity_historique
(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INT NOT NULL,
  day INT NOT NULL,
  "analyse" INT NOT NULL,
  analyse_average DOUBLE PRECISION NOT NULL,
  success INT NOT NULL,
  failed INT NOT NULL,
  success_rate DOUBLE PRECISION NOT NULL,
  max_time INT NOT NULL,
  date_enregistrement timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
