/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c assistant_ia db_user

DROP TABLE IF EXISTS ma_moulinette.actuator;

CREATE TABLE ma_moulinette.actuator
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maven_key VARCHAR(255) NOT NULL,
    nom_application VARCHAR(128) NOT NULL,
    url VARCHAR(255) NOT NULL,
    actuator_user VARCHAR(128),
    actuator_password VARCHAR(128),
    personne VARCHAR(128) NOT NULL,
    date_modification TIMESTAMP,
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
