/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.actuator_info;
CREATE TABLE ma_moulinette.actuator_info
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actuator_info_description VARCHAR(255),
    actuator_info_value VARCHAR(128),
    actuator_id INT NOT NULL
);
