/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
--- On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.anomalie_details;

CREATE TABLE ma_moulinette.anomalie_details
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  name VARCHAR(128) NOT NULL,
  bug_blocker INT NOT NULL,
  bug_critical INT NOT NULL,
  bug_info INT NOT NULL,
  bug_major INT NOT NULL,
  bug_minor INT NOT NULL,
  vulnerability_blocker INT NOT NULL,
  vulnerability_critical INT NOT NULL,
  vulnerability_info INT NOT NULL,
  vulnerability_major INT NOT NULL,
  vulnerability_minor INT NOT NULL,
  code_smell_blocker INT NOT NULL,
  code_smell_critical INT NOT NULL,
  code_smell_info INT NOT NULL,
  code_smell_major INT NOT NULL,
  code_smell_minor INT NOT NULL,
  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
