/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;
DROP TABLE IF EXISTS ma_moulinette.anomalie_details;

CREATE TABLE ma_moulinette.anomalie_details
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  name VARCHAR(128) NOT NULL,
  bug_blocker INT NOT NULL,
  bug_critical INT NOT NULL,
  bug_info INT NOT NULL,
  bug_major INT NOT NULL,
  bug_minor INT NOT NULL,
  vulnerability_blocker INT NOT NULL,
  vulnerability_critical INT NOT NULL,
  vulnerability_info INT NOT NULL,
  vulnerability_major INT NOT NULL,
  vulnerability_minor INT NOT NULL,
  code_smell_blocker INT NOT NULL,
  code_smell_critical INT NOT NULL,
  code_smell_info INT NOT NULL,
  code_smell_major INT NOT NULL,
  code_smell_minor INT NOT NULL,
  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
