/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c assistant_ia db_user

DROP TABLE IF EXISTS ma_moulinette.anomalie;

CREATE TABLE ma_moulinette.anomalie
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  project_name VARCHAR(128) NOT NULL,
  anomalie_total INT NOT NULL,
  dette_minute INT NOT NULL,
  dette_reliability_minute INT NOT NULL,
  dette_vulnerability_minute INT NOT NULL,
  dette_code_smell_minute INT NOT NULL,
  dette_reliability VARCHAR(32) NOT NULL,
  dette_vulnerability VARCHAR(32) NOT NULL,
  dette VARCHAR(32) NOT NULL,
  dette_code_smell VARCHAR(32) NOT NULL,
  frontend INT NOT NULL,
  backend INT NOT NULL,
  autre INT NOT NULL,
  inconnu INT NOT NULL,
  blocker INT NOT NULL,
  critical INT NOT NULL,
  major INT NOT NULL,
  info INT NOT NULL,
  minor INT NOT NULL,
  bug INT NOT NULL,
  vulnerability INT NOT NULL,
  code_smell INT NOT NULL,
  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
