/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.batch_execution;

CREATE TABLE ma_moulinette.batch_execution (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_traitement VARCHAR(32) NOT NULL,
    execution_id VARCHAR(36) NOT NULL,
    traitement_id VARCHAR(36) NOT NULL,
    mode_collecte VARCHAR(32) NOT NULL,
    utilisateur_collecte VARCHAR(320),
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
