/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.batch_traitement;

CREATE TABLE ma_moulinette.batch_traitement
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode_collecte VARCHAR(32) NOT NULL,
    activated BOOLEAN NOT NULL DEFAULT false,
    success BOOLEAN,
    pending BOOLEAN,
    in_progress BOOLEAN NOT NULL DEFAULT false,
    titre VARCHAR(32) NOT NULL,
    portefeuille VARCHAR(32) NOT NULL,
    nombre_projet INT NOT NULL,
    responsable VARCHAR(128) NOT NULL,
    responsable_short VARCHAR(64) NOT NULL,
    debut_traitement TIMESTAMPTZ,
    fin_traitement TIMESTAMPTZ,
    traitement_id VARCHAR(36),
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
