/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c assistant_ia db_user

DROP TABLE IF EXISTS ma_moulinette.batch_profiling;

CREATE TABLE ma_moulinette.batch_profiling (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portefeuille VARCHAR(64) NOT NULL,
    execution_reference VARCHAR(255),
    nb_projets INT NOT NULL,
    temps_total DOUBLE PRECISION NOT NULL,
    temps_moyen DOUBLE PRECISION NOT NULL,
    memoire_peak DOUBLE PRECISION NOT NULL,
    memoire_moyenne DOUBLE PRECISION NOT NULL,
    utilisateur VARCHAR(128) NOT NULL,
    date_execution TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
