/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c assistant_ia db_user

DROP TABLE IF EXISTS ma_moulinette.batch_execution_journal;

CREATE TABLE ma_moulinette.batch_execution_journal (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_projet VARCHAR(128) NOT NULL,
    portefeuille VARCHAR(32) NOT NULL,
    code INT NOT NULL,
    compte_rendu BYTEA NOT NULL,
    date_execution TIMESTAMPTZ NOT NULL,
    job_id INT NOT NULL
);
