/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.batch;

\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.batch;

CREATE TABLE ma_moulinette.batch
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  automatique BOOLEAN NOT NULL DEFAULT false,
  activated BOOLEAN NOT NULL,
  titre VARCHAR(32) NOT NULL,
  description VARCHAR(128) NOT NULL,
  responsable VARCHAR(128) NOT NULL,
  responsable_short VARCHAR(64) NOT NULL,
  portefeuille VARCHAR(32) NOT NULL,
  nombre_projet INT NOT NULL,
  execution VARCHAR(8) DEFAULT NULL::VARCHAR,
  traitement_id VARCHAR(36) NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL
);
