/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.1.0 - 2026-05-12                  ##
##           scans projet                         ##
##                                                ##
####################################################*/

--- 2026-05-08 : un scan = un rapport DependencyCheck pour
--- (projet, version, date). Vue par projet ; compteurs pre-calcules.
--- 2026-05-12 : ajout de metadata parent_label/version et archetype_version transmises par la CI a l'upload.

-- Lien vers la queue d'ingestion source (pour audit/retraitement)
-- Lien vers la queue d'ingestion source (pour audit/retraitement)
-- group:artifact (compose)
-- Date du scan (extraite de projectInfo.reportDate du JSON)
-- Version du moteur OWASP DependencyCheck (scanInfo.engineVersion)
-- Compteurs pre-calcules (éviter COUNT() au rendering)
  -- parent_label    : "springboot-archetype-config" (archetype) ou "groupId:artifactId" (legacy) ou NULL
  -- parent_version  : version du BOM/parent (springboot-archetype-config.version | socleVersion | parent.version)
  -- archetype_version : version du template de generation (springboot-archetype.version), NULL hors archetype

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.dc_scan CASCADE;

CREATE TABLE ma_moulinette.dc_scan
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_id BIGINT NULL,
  maven_key VARCHAR(511) NOT NULL,
  project_group VARCHAR(255) NOT NULL,
  project_artifact VARCHAR(255) NOT NULL,
  project_version VARCHAR(64)  NOT NULL,
  scan_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  engine_version VARCHAR(32) NULL,
  report_schema VARCHAR(16) NULL,                  -- ex: 1.1
  dep_count_total INTEGER NOT NULL DEFAULT 0,
  dep_count_vulnerable INTEGER NOT NULL DEFAULT 0,
  cve_count_critical INTEGER NOT NULL DEFAULT 0,
  cve_count_high INTEGER NOT NULL DEFAULT 0,
  cve_count_medium INTEGER NOT NULL DEFAULT 0,
  cve_count_low INTEGER NOT NULL DEFAULT 0,
  cve_count_info INTEGER NOT NULL DEFAULT 0,
  cve_count_total INTEGER NOT NULL DEFAULT 0,
  parent_label      VARCHAR(128) NULL,
  parent_version    VARCHAR(64)  NULL,
  archetype_version VARCHAR(64)  NULL,
  is_latest_overall BOOLEAN NOT NULL DEFAULT FALSE,
  is_latest_release BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
);
