/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V1.0.0 - 05/04/2026                  ##
##                                                ##
####################################################*/

--- 2026-04-05 : Ajout de la table groupe_fonctionnel

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.groupe_fonctionnel;

CREATE TABLE ma_moulinette.groupe_fonctionnel
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  groupe_fonctionnel character varying(128) NOT NULL,
  description character varying(255) NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
