/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.hotspot_details;

CREATE TABLE ma_moulinette.hotspot_details
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    maven_key VARCHAR(255) NOT NULL,
    version VARCHAR(32) NOT NULL,
    date_version TIMESTAMPTZ NOT NULL,

    security_category VARCHAR(64) NOT NULL,
    rule_key VARCHAR(128) NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    severity VARCHAR(8) NOT NULL,
    status VARCHAR(16) NOT NULL,
    resolution VARCHAR(16),

    niveau INT NOT NULL,
    frontend INT NOT NULL,
    backend INT NOT NULL,
    autre INT NOT NULL,

    file_name VARCHAR(128) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    line INT NOT NULL,
    message VARCHAR(255) NOT NULL,

    hotspot_key VARCHAR(32) NOT NULL,

    mode_collecte VARCHAR(32),
    utilisateur_collecte VARCHAR(320),

    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
