/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.hotspot_owasp;

CREATE TABLE ma_moulinette.hotspot_owasp
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referential_owasp INT NOT NULL DEFAULT 2017,
    maven_key VARCHAR(255) NOT NULL,
    version VARCHAR(32) NOT NULL,
    date_version TIMESTAMPTZ NOT NULL,
    menace VARCHAR(8) NOT NULL,
    security_category VARCHAR(64) NOT NULL,
    rule_key VARCHAR(255) NOT NULL,
    probability VARCHAR(8) NOT NULL,
    status VARCHAR(16) NOT NULL,
    resolution VARCHAR(16),
    niveau INT NOT NULL,
    mode_collecte VARCHAR(32),
    utilisateur_collecte VARCHAR(320),
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
