/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c assistant_ia db_user

DROP TABLE IF EXISTS ma_moulinette.information_projet;

CREATE TABLE ma_moulinette.information_projet
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    maven_key VARCHAR(255) NOT NULL,
    analyse_key VARCHAR(32) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    project_version VARCHAR(32) NOT NULL,
    type VARCHAR(32) NOT NULL,

    version_sonar INT NOT NULL DEFAULT 0,
    version_release_sonar INT NOT NULL DEFAULT 0,
    version_snapshot_sonar INT NOT NULL DEFAULT 0,
    version_autre_sonar INT NOT NULL DEFAULT 0,

    mode_collecte VARCHAR(32),
    utilisateur_collecte VARCHAR(320),

    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
