/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.ma_moulinette;

CREATE TABLE ma_moulinette.ma_moulinette
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version VARCHAR(16) NOT NULL,
  date_version TIMESTAMPTZ NOT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
