/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.mesures;

CREATE TABLE ma_moulinette.mesures
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maven_key VARCHAR(255) NOT NULL,
  project_name VARCHAR(128) NOT NULL,
  lines INT NOT NULL,
  ncloc INT NOT NULL,
  language_distribution JSON NOT NULL,
  coverage DOUBLE PRECISION NOT NULL,
  files INT NOT NULL,
  classes INT NOT NULL,
  functions INT NOT NULL,
  sqale_debt_ratio DOUBLE PRECISION NOT NULL,
  duplicated_lines_density DOUBLE PRECISION NOT NULL,
  tests INT NOT NULL,
  issues INT NOT NULL,
  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
