/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;
DROP TABLE IF EXISTS ma_moulinette.owasp_top10;

CREATE TABLE ma_moulinette.owasp_top10 (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    year INT NOT NULL,
    category VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    lien VARCHAR(128) NOT NULL,

    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
