/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.1.0 - 18/07/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
---              On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.
--- 2026-07-18 : Ajout de la colonne source pour distinguer les facettes des tags.


-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.owasp;

CREATE TABLE ma_moulinette.owasp
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  referential_owasp INT NOT NULL DEFAULT 2017,
  maven_key VARCHAR(255) NOT NULL,
  version VARCHAR(32) NOT NULL,
  date_version TIMESTAMPTZ NOT NULL,

  effort_total INT NOT NULL,

  -- 'facet' (classification officielle SonarQube owaspTop10/owaspTop10-2021)
  -- ou 'tag' (secours par tag owasp-aXX quand la facette ne renvoie rien) :
  -- cf. mkDocs/docs/ma-moulinette/application/owasp.md.
  source VARCHAR(10) NOT NULL DEFAULT 'facet',

  a1 INT NOT NULL,
  a2 INT NOT NULL,
  a3 INT NOT NULL,
  a4 INT NOT NULL,
  a5 INT NOT NULL,
  a6 INT NOT NULL,
  a7 INT NOT NULL,
  a8 INT NOT NULL,
  a9 INT NOT NULL,
  a10 INT NOT NULL,

  a1_blocker INT NOT NULL,
  a1_critical INT NOT NULL,
  a1_major INT NOT NULL,
  a1_info INT NOT NULL,
  a1_minor INT NOT NULL,

  a2_blocker INT NOT NULL,
  a2_critical INT NOT NULL,
  a2_major INT NOT NULL,
  a2_info INT NOT NULL,
  a2_minor INT NOT NULL,

  a3_blocker INT NOT NULL,
  a3_critical INT NOT NULL,
  a3_major INT NOT NULL,
  a3_info INT NOT NULL,
  a3_minor INT NOT NULL,

  a4_blocker INT NOT NULL,
  a4_critical INT NOT NULL,
  a4_major INT NOT NULL,
  a4_info INT NOT NULL,
  a4_minor INT NOT NULL,

  a5_blocker INT NOT NULL,
  a5_critical INT NOT NULL,
  a5_major INT NOT NULL,
  a5_info INT NOT NULL,
  a5_minor INT NOT NULL,

  a6_blocker INT NOT NULL,
  a6_critical INT NOT NULL,
  a6_major INT NOT NULL,
  a6_info INT NOT NULL,
  a6_minor INT NOT NULL,

  a7_blocker INT NOT NULL,
  a7_critical INT NOT NULL,
  a7_major INT NOT NULL,
  a7_info INT NOT NULL,
  a7_minor INT NOT NULL,

  a8_blocker INT NOT NULL,
  a8_critical INT NOT NULL,
  a8_major INT NOT NULL,
  a8_info INT NOT NULL,
  a8_minor INT NOT NULL,

  a9_blocker INT NOT NULL,
  a9_critical INT NOT NULL,
  a9_major INT NOT NULL,
  a9_info INT NOT NULL,
  a9_minor INT NOT NULL,

  a10_blocker INT NOT NULL,
  a10_critical INT NOT NULL,
  a10_major INT NOT NULL,
  a10_info INT NOT NULL,
  a10_minor INT NOT NULL,

  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),

  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
