/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.1.0 - 07/04/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-04-07 : Renommage titre et groupe en portefeuille et groupe_fonctionnel et modification de la longueur du champ groupe_fonctionnel

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.portefeuille;

CREATE TABLE ma_moulinette.portefeuille
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portefeuille VARCHAR(32) NOT NULL,
  groupe_fonctionnel VARCHAR(128) NOT NULL,
  liste json NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
