/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.portefeuille;

CREATE TABLE ma_moulinette.portefeuille
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre VARCHAR(32) NOT NULL,
  groupe VARCHAR(32) NOT NULL,
  liste json NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
