/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.profiles_historique;

CREATE TABLE ma_moulinette.profiles_historique
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_courte TIMESTAMPTZ NOT NULL,
    language VARCHAR(16) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    action VARCHAR(16) NOT NULL,
    auteur VARCHAR(64) NOT NULL,
    rule VARCHAR(128) NOT NULL,
    description text NOT NULL,
    detail bytea NOT NULL,
    date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
