/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.properties;

CREATE TABLE ma_moulinette.properties
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  projet_bd INT NOT NULL,
  projet_sonar INT NOT NULL,
  profil_bd INT NOT NULL,
  profil_sonar INT NOT NULL,
  date_creation TIMESTAMPTZ NOT NULL,
  date_modification_projet TIMESTAMP DEFAULT NULL,
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
