/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.1 - 28/06/2026                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-06-28 : On passe le script en automatique avec l'utilisateur postgres, puis on applique le script grants.sql.
---              On supprime l'utilisateur db_user pour éviter de passer le mot de passe une seconde fois.

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette;

DROP TABLE IF EXISTS ma_moulinette.properties;

CREATE TABLE ma_moulinette.properties
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  projet_bd INT NOT NULL,
  projet_sonar INT NOT NULL,
  profil_bd INT NOT NULL,
  profil_sonar INT NOT NULL,
  date_creation TIMESTAMPTZ NOT NULL,
  date_modification_projet TIMESTAMP DEFAULT NULL,
  date_modification_profil TIMESTAMP DEFAULT NULL
);
