/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.repartition;

CREATE TABLE ma_moulinette.repartition
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  maven_key VARCHAR(255) NOT NULL,
  name VARCHAR(128) NOT NULL,
  setup BIGINT NOT NULL,

  -- Colonnes analytiques
  bug_blocker INT DEFAULT 0,
  bug_critical INT DEFAULT 0,
  bug_major INT DEFAULT 0,
  bug_minor INT DEFAULT 0,
  bug_info INT DEFAULT 0,

  vulnerability_blocker INT DEFAULT 0,
  vulnerability_critical INT DEFAULT 0,
  vulnerability_major INT DEFAULT 0,
  vulnerability_minor INT DEFAULT 0,
  vulnerability_info INT DEFAULT 0,

  code_smell_blocker INT DEFAULT 0,
  code_smell_critical INT DEFAULT 0,
  code_smell_major INT DEFAULT 0,
  code_smell_minor INT DEFAULT 0,
  code_smell_info INT DEFAULT 0,

  -- frontend
  frontend INT DEFAULT 0,
  frontend_bug_blocker INT DEFAULT 0,
  frontend_bug_critical INT DEFAULT 0,
  frontend_bug_major INT DEFAULT 0,
  frontend_bug_minor INT DEFAULT 0,
  frontend_bug_info INT DEFAULT 0,

  frontend_vulnerability_blocker INT DEFAULT 0,
  frontend_vulnerability_critical INT DEFAULT 0,
  frontend_vulnerability_major INT DEFAULT 0,
  frontend_vulnerability_minor INT DEFAULT 0,
  frontend_vulnerability_info INT DEFAULT 0,

  frontend_code_smell_blocker INT DEFAULT 0,
  frontend_code_smell_critical INT DEFAULT 0,
  frontend_code_smell_major INT DEFAULT 0,
  frontend_code_smell_minor INT DEFAULT 0,
  frontend_code_smell_info INT DEFAULT 0,

  -- backend
  backend INT DEFAULT 0,
  backend_bug_blocker INT DEFAULT 0,
  backend_bug_critical INT DEFAULT 0,
  backend_bug_major INT DEFAULT 0,
  backend_bug_minor INT DEFAULT 0,
  backend_bug_info INT DEFAULT 0,

  backend_vulnerability_blocker INT DEFAULT 0,
  backend_vulnerability_critical INT DEFAULT 0,
  backend_vulnerability_major INT DEFAULT 0,
  backend_vulnerability_minor INT DEFAULT 0,
  backend_vulnerability_info INT DEFAULT 0,

  backend_code_smell_blocker INT DEFAULT 0,
  backend_code_smell_critical INT DEFAULT 0,
  backend_code_smell_major INT DEFAULT 0,
  backend_code_smell_minor INT DEFAULT 0,
  backend_code_smell_info INT DEFAULT 0,

  -- autre
  autre INT DEFAULT 0,
  autre_bug_blocker INT DEFAULT 0,
  autre_bug_critical INT DEFAULT 0,
  autre_bug_major INT DEFAULT 0,
  autre_bug_minor INT DEFAULT 0,
  autre_bug_info INT DEFAULT 0,

  autre_vulnerability_blocker INT DEFAULT 0,
  autre_vulnerability_critical INT DEFAULT 0,
  autre_vulnerability_major INT DEFAULT 0,
  autre_vulnerability_minor INT DEFAULT 0,
  autre_vulnerability_info INT DEFAULT 0,

  autre_code_smell_blocker INT DEFAULT 0,
  autre_code_smell_critical INT DEFAULT 0,
  autre_code_smell_major INT DEFAULT 0,
  autre_code_smell_minor INT DEFAULT 0,
  autre_code_smell_info INT DEFAULT 0,

  -- inconnu
  inconnu INT DEFAULT 0,
  inconnu_bug_blocker INT DEFAULT 0,
  inconnu_bug_critical INT DEFAULT 0,
  inconnu_bug_major INT DEFAULT 0,
  inconnu_bug_minor INT DEFAULT 0,
  inconnu_bug_info INT DEFAULT 0,

  inconnu_vulnerability_blocker INT DEFAULT 0,
  inconnu_vulnerability_critical INT DEFAULT 0,
  inconnu_vulnerability_major INT DEFAULT 0,
  inconnu_vulnerability_minor INT DEFAULT 0,
  inconnu_vulnerability_info INT DEFAULT 0,

  inconnu_code_smell_blocker INT DEFAULT 0,
  inconnu_code_smell_critical INT DEFAULT 0,
  inconnu_code_smell_major INT DEFAULT 0,
  inconnu_code_smell_minor INT DEFAULT 0,
  inconnu_code_smell_info INT DEFAULT 0,

  control VARCHAR(32) NOT NULL DEFAULT 'initial',

  mode_collecte VARCHAR(32),
  utilisateur_collecte VARCHAR(320),
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
