
/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c assistant_ia db_user

DROP TABLE IF EXISTS ma_moulinette.repartition_temp;

CREATE UNLOGGED TABLE ma_moulinette.repartition_temp (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maven_key VARCHAR(255) NOT NULL,
    component TEXT NOT NULL,
    type VARCHAR(16) NOT NULL,
    severity VARCHAR(8) NOT NULL,
    setup BIGINT NOT NULL
);
