/*
####################################################
##                                                ##
##           Create TABLES                        ##
##           V2.0.0 - 30/11/2025                  ##
##                                                ##
####################################################*/

--- 2025-11-30 : Migration postGreSql 18
--- 2026-03-08 : ajout de la colonne last_activity_at

-- ⚠️ Le script doit être lancé avec l'utilisateur propriétaire du schema
\c ma_moulinette db_user;

DROP TABLE IF EXISTS ma_moulinette.utilisateur;

CREATE TABLE ma_moulinette.utilisateur
(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prenom VARCHAR(32) NOT NULL,
  nom VARCHAR(64) NOT NULL,
  avatar VARCHAR(128) DEFAULT NULL::VARCHAR,
  courriel VARCHAR(320) NOT NULL,
  roles json,
  groupe json,
  password VARCHAR(64) NOT NULL,
  actif BOOLEAN NOT NULL DEFAULT false,
  preference json NOT NULL,
  reset_password BOOLEAN DEFAULT TRUE NOT NULL,
  reset_password_count SMALLINT DEFAULT 1 NOT NULL,
  date_modification TIMESTAMP DEFAULT NULL,
  last_activity_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT NULL;
  date_enregistrement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
